[project]
name = "fastmcp-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.12.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
]
